# -*- coding: utf-8 -*-
"""Punto_1_imperatico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BqARUeRUgb1WOi4J88DSvusmHVtwm1C9
"""

# este es el enfoque imperativo
estudiantes = [
    ("Daniela", 90),
    ("Carmen", 85),
    ("lottie", 90),
    ("Juan", 75)
]

for i in range(len(estudiantes)):
    for j in range(i + 1, len(estudiantes)):
        if (estudiantes[i][1] < estudiantes[j][1]) or (
            estudiantes[i][1] == estudiantes[j][1] and estudiantes[i][0] > estudiantes[j][0]
        ):

            estudiantes[i], estudiantes[j] = estudiantes[j], estudiantes[i]

print("Imperativo:", estudiantes)